version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_JMX_PORT: 9991
    ports:
      # Exposes 29092 for external connections to the broker
      # Use kafka1:9092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - '29092:29092'
    depends_on:
      - zookeeper

  schemaregistry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    ports:
      - '8085:8085'
    depends_on:
      - zookeeper

  control-center:
    container_name: control-center
    image: confluentinc/cp-control-center:3.0.1
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8085"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    ports:
      - '9021:9021'
    depends_on:
      - zookeeper
      - kafka
      - schemaregistry

  # databases
  userservice-postgres:
    container_name: userservice-postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - '5433:5432'

  userservice:
    container_name: userservice
    image: runapp/userservice
    build: ./userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/test" ]
      interval: 1m
      timeout: 10s
      retries: 3
    ports:
      - '8083:8083'
      - '8093:8093' #grpc
    depends_on:
      - userservice-postgres

  runservice-postgres:
    container_name: runservice-postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - '5434:5432'

  runservice:
    container_name: runservice
    image: runapp/runservice
    build: ./runservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5434/postgres
      MONGODB_URI: mongodb://mongodb:27017/docker-db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/test" ]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      - mongodb
      - runservice-postgres
    ports:
      - '8082:8082'
      - '8092:8092' #grpc

  metric-aggregation-postgres:
    container_name: metric-aggregation-postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - '5435:5432'


  mongodb:
    container_name: mongodb
    image: mongo:${MONGO_VERSION}
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: password
#      MONGO_INITDB_DATABASE: runapp
#      MONGO_INITDB_DATABASE: runapp
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '27017:27017'