version: "3"

services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - 5433:5432
    hostname: postgres
#    network_mode: host

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dasha
    ports:
      - 27017:27017
    hostname: mongodb
#    network_mode: host
  userservice:
    build: userservice/
#    networks:
#      default:
#        aliases:
#          - userservice.local.own
#    network_mode: host
    ports:
      - 8081:8080
    hostname: userservice
    depends_on:
      - postgres

  runservice:
    build: runservice/
#    networks:
#      default:
#        aliases:
#          - runservice.local.own
#    network_mode: host
    ports:
      - 8082:8080
    hostname: runservice
    depends_on:
      - mongodb

networks:
  host:
    external: true
