version: "3"

services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - 5433:5432
    hostname: postgres
#    network_mode: host

  mongodb:
    image: mongo
#    container_name: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=runapp
    ports:
      - '27017:27017'
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - '8081:8081'
    depends_on:
      mongodb:
        condition: service_healthy

  userservice:
    build: userservice/
#    networks:
#      default:
#        aliases:
#          - userservice.local.own
#    network_mode: host
    ports:
      - 8091:8080
    hostname: userservice
    depends_on:
      - postgres

  runservice:
    build: runservice/
#    networks:
#      default:
#        aliases:
#          - runservice.local.own
#    network_mode: host
    ports:
      - 8092:8080
    hostname: runservice
    depends_on:
      - mongodb

volumes:
  data: {}
#networks:
#  host:
#    external: true
