version: "3"

services:
  userservice-postgres:
    container_name: userservice-postgres
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - '5433:5432'

  runservice-postgres:
    container_name: runservice-postgres
    image: postgres:11.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasha
    ports:
      - '5434:5432'
    hostname: postgres

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=runapp
    ports:
      - '27017:27017'
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  userservice:
    container_name: userservice
    build: userservice/
    ports:
      - '8091:8091'
      - '9091:9091'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/test" ]
      interval: 1m
      timeout: 10s
      retries: 3
    hostname: userservice
    depends_on:
      - userservice-postgres

  runservice:
    container_name: runservice
    build: runservice/
    ports:
      - '8092:8092'
      - '9092:9092'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - mongodb
      - runservice-postgres

volumes:
  data: {}
